export enum Healthcare {
  PRIMARY_HEALTHCARE = 'PRIMARY_HEALTHCARE',
  SPECIALTY_HEALTHCARE = 'SPECIALTY_HEALTHCARE',
  EMERGENCY_HEALTHCARE = 'EMERGENCY_HEALTHCARE',
  MENTAL_HEALTHCARE = 'MENTAL_HEALTHCARE',
}
